ARG REPO=zpcloud
ARG RELEASE=latest

FROM $REPO/zp-operator:$RELEASE as base

MAINTAINER ZoomPhant DEV <dev@zoomphant.com>

##
## Labels
##
LABEL name="ZoomPhant Collector Kubernetes Operator" image="zoomphant-operator" vendor="Zervice"

ENV GIN_MODE release

ENTRYPOINT ["/manager"]