ARG REPO=zpcloud
ARG RELEASE=latest

FROM $REPO/collector:$RELEASE as base

MAINTAINER ZoomPhant DEV <dev@zoomphant.com>

##
## Labels
##
LABEL name="ZoomPhant Collector" image="zoomphant-collector" vendor="Zervice"

ENV GIN_MODE release

ENTRYPOINT ["/scripts/start.sh"]