ARG REPO=zpcloud
ARG RELEASE=latest

FROM $REPO/zoomphant-pack:$RELEASE as base

MAINTAINER ZoomPhant DEV <dev@zoomphant.com>

##
## Labels
##
LABEL name="ZoomPhant AIO Pack" image="zoomphant-pack" vendor="ZoomPhant"

EXPOSE 80

# SYSLOG port
EXPOSE 1514

VOLUME /data

ENTRYPOINT ["/scripts/startup.sh"]
