ARG REPO=zpcloud
ARG RELEASE=latest

FROM $REPO/zoomphant-aio:$RELEASE as base

MAINTAINER ZoomPhant DEV <dev@zoomphant.com>

##
## Labels
##
LABEL name="ZoomPhant AIO Package" image="zoomphant-aio" vendor="Zervice"


EXPOSE 80

EXPOSE 1514

VOLUME /data

ENTRYPOINT ["/scripts/startup.sh"]
