name: ZP AIO Build

on:
  push:
    paths:
      - 'releases/**'
      
  workflow_dispatch:
    
  schedule:
    - cron: "0 0 * * *"

env:
  REPO_BASE: ${{ vars.REPO_BASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build

    steps:
    - uses: actions/checkout@v4

    - name: Show base
      run: echo "$GITHUB_CONTEXT"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login ZP Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.ZPDOCKER_REGISTRY }}
        username: ${{ vars.ZPDOCKER_USERNAME }}
        password: ${{ secrets.ZPDOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: ./k8s/build.sh -l
